misc:
    model_name: "debug"
    base_model_name: "google/mt5-small"
    kind: "2way"
    alpha1: 0.5
    alpha2: 0.25
    dataset: "./data/dataset.jsonl.zst"
    dev_size: 0.05
    subsample: true
    subsample_size: 1000
    seed: 0

batch:
    train_size: 8
    eval_size: 8
    accumulation: 1

train:
    lr: 2e-5
    weight_decay: 0.01
    max_grad_norm: 1.0
    max_steps: 100
    lr_scheduler: "linear"
    warmup_ratio: 0.1
