misc:
    model_name: "debug"
    base_model_name: "google/mt5-small"
    kind: "1way"
    alpha1: 0.5
    alpha2: 0.25
    dataset: "./data/dataset.jsonl.zst"
    dev_size: 0.05
    subsample: false
    seed: 0

batch:
    train_size: 64
    eval_size: 64
    accumulation: 16

train:
    lr: 5e-5
    weight_decay: 0.1
    max_grad_norm: 1.0
    max_steps: 5000
    lr_scheduler: "cosine"
    warmup_ratio: 0.06
